FORMAT: 1A
HOST: http://cpsc-2030-fp.apiblueprint.org/

# cpsc-2030-fp

# Group Auth

## Login [/login]

### Authantication [POST]
+ Request (application/json)
    + Attributes
        + email: email@domain.com (string, required)
        + password: mySuperPassword (string, required)
+ Response 200 (application/json)
    + Attributes
        + token (string)
        + user (User)

# Group Article

## List [/articles]

### List All [GET]

+ Response 200 (application/json)

    + Attributes (array[Article])

### Create [POST]

+ Request (application/json)
    + Attributes (Article)

+ Response 200 (application/json)
    + Attributes (Article)
        + message: Artilce was created (string)


## Single [/article/{id}]

+ Parameters
    + id (number) - Article id 

### Details [GET]

+ Response 200 (application/json)

    + Attributes (Article)

### Update [PUT]

+ Request (application/json)
    + Attributes (Article)

+ Response 200 (application/json)

    + Attributes (Article)
    
### Delete [DELETE]

+ Response 200 (application/json)

    + Attributes 
        + message: Article was deleted (string)


# Group Page

## List [/pages]

### List All [GET]

+ Response 200 (application/json)

    + Attributes (array[Page])

### Create [POST]

+ Request (application/json)
    + Attributes (Page)

+ Response 200 (application/json)
    + Attributes (Page)
        + message: Page was created (string)
        
## Single [/pages/{id}]

+ Parameters
    + id (number) - Page id 

### Details [GET]

+ Response 200 (application/json)

    + Attributes (Article)

### Update [PUT]

+ Request (application/json)
    + Attributes (Page)

+ Response 200 (application/json)

    + Attributes (Article)
    
### Delete [DELETE]

+ Response 200 (application/json)

    + Attributes 
        + message: Article was deleted (string)

# Group User


## List [/users]

### List All [GET]

+ Response 200 (application/json)

    + Attributes (array[User])

### Create [POST]

+ Request (application/json)
    + Attributes (User)

+ Response 200 (application/json)
    + Attributes (User)
        + message: User was created
        
## Single [/users/{id}]

+ Parameters
    + id (number) - User id 

### Details [GET]

+ Response 200 (application/json)

    + Attributes (Article)

### Update [PUT]

+ Request (application/json)
    + Attributes (User)

+ Response 200 (application/json)

    + Attributes (Article)
    
### Delete [DELETE]

+ Response 200 (application/json)

    + Attributes 
        + message: User was deleted (string)

## Data Structures

### Article
+ id (number)
+ title: title (string, required)
+ content: semple conetent (string)
+ date_created: `2014-11-11T08:40:51.620Z` (string, required)
+ last_edited: `2014-11-11T08:40:51.620Z` (string)
+ user_id (number, required)


### Page
+ id (number)
+ name (string)
+ cover_image
+ url (string)
+ date_created: `2014-11-11T08:40:51.620Z` (string, required)
+ last_edited: `2014-11-11T08:40:51.620Z` (string)
+ user_id (number, required)

### User
* id (number, required)
* email: email@domain.com (string, required)
* password: mySuperPassword (string, required)
* first_name: Steve (string, required)
* last_name: Jobs (string, required)
* bio (string)
* user_role: HR (string, required)
* last_login: `2014-11-11T08:40:51.620Z` (string)